services:
  frontend:
    container_name: login
    image: docker.io/krakekrake/swe40006:frontend
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 3001:80

  backend:
    container_name: login-api
    volumes:
      - ../users.sqlite3:/api/users.sqlite3:z
    image: docker.io/krakekrake/swe40006:backend
    build:
      context: ../../Credit
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - 8001:8000
